#!/usr/bin/env pwsh
# Release Build Script for MyLocalBackup
# Usage: ./release-build.ps1 -Version "2.0.0"

param(
    [Parameter(Mandatory=$true)]
    [string]$Version
)

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$publishDir = "$root\Staging\Publish"
$msiDir = "$root\Staging\MyLocalBackup_Setup"

Write-Host "=== MyLocalBackup Release Build v$Version ===" -ForegroundColor Cyan

# Step 1: Publish
Write-Host "`n[1/4] Publishing..." -ForegroundColor Yellow
if (Test-Path $publishDir) { Remove-Item $publishDir -Recurse -Force }
dotnet publish "$root/MyLocalBackup.UI/MyLocalBackup.UI.csproj" -c Release -r win-x64 --self-contained -o $publishDir | Out-Null
if ($LASTEXITCODE -ne 0) { throw "Publish failed" }

# Step 2: Stage and build MSI
Write-Host "[2/4] Building MSI..." -ForegroundColor Yellow
if (Test-Path "C:\MLB_Staging") { Remove-Item "C:\MLB_Staging\*" -Recurse -Force }
New-Item -ItemType Directory -Path "C:\MLB_Staging" -Force | Out-Null
Copy-Item "$publishDir\*" "C:\MLB_Staging\" -Recurse -Force

# Always regenerate Files.wxs from actual publish output so it never goes stale
Write-Host "  Regenerating Files.wxs from publish output..." -ForegroundColor Gray
$filesWxs = "$msiDir/Files.wxs"
$stagingBase = "C:\MLB_Staging"

function Get-SafeId($s) { return ($s -replace '[^a-zA-Z0-9]', '_') }

# Build ComponentGroup for root files (AppFiles)
$rootComponents = [System.Collections.Generic.List[string]]::new()
Get-ChildItem "$stagingBase" -File | ForEach-Object {
    $id = "fc_$(Get-SafeId $_.Name)"
    $rootComponents.Add("    <Component Id='$id' Guid='*' Directory='INSTALLFOLDER'><File Source='$stagingBase\$($_.Name)' /></Component>")
}

# Build one ComponentGroup per locale subdirectory
$localeFragments = [System.Collections.Generic.List[string]]::new()
Get-ChildItem "$stagingBase" -Directory | ForEach-Object {
    $dirName = $_.Name
    $dirId = "dir_$(Get-SafeId $dirName)"
    $groupId = "AppFiles_$(Get-SafeId $dirName)"
    $files = Get-ChildItem $_.FullName -File
    if ($files.Count -eq 0) { return }

    $comps = $files | ForEach-Object {
        $id = "fc_$(Get-SafeId $dirName)_$(Get-SafeId $_.Name)"
        "    <Component Id='$id' Guid='*' Directory='$dirId'><File Source='$stagingBase\$dirName\$($_.Name)' /></Component>"
    }

    $localeFragments.Add(@"
  <Fragment>
    <DirectoryRef Id='INSTALLFOLDER'>
      <Directory Id='$dirId' Name='$dirName' />
    </DirectoryRef>
  </Fragment>
  <Fragment>
    <ComponentGroup Id='$groupId'>
$($comps -join "`n")
    </ComponentGroup>
  </Fragment>
"@)
}

$wxsContent = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- AUTO-GENERATED by release-build.ps1 — do not edit manually -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="AppFiles">
$($rootComponents -join "`n")
    </ComponentGroup>
  </Fragment>
$($localeFragments -join "`n")
</Wix>
"@
Set-Content $filesWxs -Value $wxsContent -Encoding UTF8
Write-Host "  Files.wxs regenerated ($($rootComponents.Count) root + $($localeFragments.Count) locale groups)" -ForegroundColor Gray

Push-Location $msiDir
wix build Package.wxs Files.wxs -d "Version=$Version" -o MyLocalBackupSetup.msi
if ($LASTEXITCODE -ne 0) { Pop-Location; throw "MSI build failed" }
Pop-Location

# Step 3: Compute MSI hash
Write-Host "[3/4] Computing MSI hash..." -ForegroundColor Yellow
$msiHash = (Get-FileHash "$msiDir\MyLocalBackupSetup.msi" -Algorithm SHA256).Hash.ToLower()

# Step 4: Copy to Desktop
Write-Host "[4/4] Copying MSI to Desktop..." -ForegroundColor Yellow
Copy-Item "$msiDir\MyLocalBackupSetup.msi" "$env:USERPROFILE\Desktop\MyLocalBackupSetup_v$Version.msi" -Force

Write-Host "`n=== Build Complete ===" -ForegroundColor Green
Write-Host "MSI: $env:USERPROFILE\Desktop\MyLocalBackupSetup_v$Version.msi"
Write-Host "MSI SHA256: $msiHash"
Write-Host "`nInclude this in your GitHub release notes:"
Write-Host "SHA256: $msiHash" -ForegroundColor Cyan
