#!/usr/bin/env pwsh
# Release Build Script for MyLocalBackup
# Usage: ./release-build.ps1 -Version "X.Y.Z"

param(
    [Parameter(Mandatory=$true)]
    [string]$Version
)

# Validate version format (X.Y.Z)
if ($Version -notmatch '^\d+\.\d+\.\d+$') {
    throw "Invalid version format '$Version'. Expected format: X.Y.Z (e.g., 0.7.1)"
}

$ErrorActionPreference = "Stop"
$root = $PSScriptRoot
$publishDir = "$root\Staging\Publish"
$msiDir = "$root\Staging\MyLocalBackup_Setup"
$stagingBase = "$root\Staging\MLB_Build"

Write-Host "=== MyLocalBackup Release Build v$Version ===" -ForegroundColor Cyan

# Step 1: Publish
Write-Host "`n[1/5] Publishing..." -ForegroundColor Yellow
if (Test-Path $publishDir) { Remove-Item $publishDir -Recurse -Force }
dotnet publish "$root/MyLocalBackup.UI/MyLocalBackup.UI.csproj" -c Release -r win-x64 --self-contained -p:PublishReadyToRun=true -o $publishDir | Out-Null
if ($LASTEXITCODE -ne 0) { throw "Publish failed" }

# Verify publish output contains expected files
if (-not (Get-ChildItem $publishDir -Filter "*.exe" | Select-Object -First 1)) {
    throw "Publish succeeded but no .exe found in output directory"
}

# Strip PDB files — not needed in release MSI (matches PackagePortable.ps1 behavior)
Get-ChildItem -Path $publishDir -Filter "*.pdb" -Recurse | Remove-Item
Write-Host "  PDB files stripped from publish output" -ForegroundColor Gray

# Step 2: Stage and build MSI
Write-Host "[2/5] Building MSI..." -ForegroundColor Yellow

# Clean up old build artifacts from previous builds
Get-ChildItem $msiDir -Include "*.msi","*.exe","*.wixpdb","*.cab" -File | ForEach-Object {
    Remove-Item $_.FullName -Force
    Write-Host "  Cleaned old artifact: $($_.Name)" -ForegroundColor Gray
}
if (Test-Path $stagingBase) { Remove-Item $stagingBase -Recurse -Force }
New-Item -ItemType Directory -Path $stagingBase -Force | Out-Null
Copy-Item "$publishDir\*" "$stagingBase\" -Recurse -Force

# Always regenerate Files.wxs from actual publish output so it never goes stale
Write-Host "  Regenerating Files.wxs from publish output..." -ForegroundColor Gray
$filesWxs = "$msiDir/Files.wxs"
## $stagingBase is set above near the top of the script

function Get-SafeId($s) { return ($s -replace '[^a-zA-Z0-9]', '_') }

# Build ComponentGroup for root files (AppFiles)
$rootComponents = [System.Collections.Generic.List[string]]::new()
Get-ChildItem "$stagingBase" -File | ForEach-Object {
    $id = "fc_$(Get-SafeId $_.Name)"
    $rootComponents.Add("    <Component Id='$id' Guid='*' Directory='INSTALLFOLDER'><File Source='$stagingBase\$($_.Name)' /></Component>")
}

# Build one ComponentGroup per locale subdirectory
$localeFragments = [System.Collections.Generic.List[string]]::new()
$localeGroupIds = [System.Collections.Generic.List[string]]::new()
Get-ChildItem "$stagingBase" -Directory | ForEach-Object {
    $dirName = $_.Name
    $dirId = "dir_$(Get-SafeId $dirName)"
    $groupId = "AppFiles_$(Get-SafeId $dirName)"
    $files = Get-ChildItem $_.FullName -File
    if ($files.Count -eq 0) { return }

    $localeGroupIds.Add($groupId)
    $comps = $files | ForEach-Object {
        $id = "fc_$(Get-SafeId $dirName)_$(Get-SafeId $_.Name)"
        "    <Component Id='$id' Guid='*' Directory='$dirId'><File Source='$stagingBase\$dirName\$($_.Name)' /></Component>"
    }

    $localeFragments.Add(@"
  <Fragment>
    <DirectoryRef Id='INSTALLFOLDER'>
      <Directory Id='$dirId' Name='$dirName' />
    </DirectoryRef>
  </Fragment>
  <Fragment>
    <ComponentGroup Id='$groupId'>
$($comps -join "`n")
    </ComponentGroup>
  </Fragment>
"@)
}

$wxsContent = @"
<?xml version="1.0" encoding="utf-8"?>
<!-- AUTO-GENERATED by release-build.ps1 — do not edit manually -->
<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="AppFiles">
$($rootComponents -join "`n")
    </ComponentGroup>
  </Fragment>
$($localeFragments -join "`n")
</Wix>
"@
Set-Content $filesWxs -Value $wxsContent -Encoding UTF8
Write-Host "  Files.wxs regenerated ($($rootComponents.Count) root + $($localeFragments.Count) locale groups)" -ForegroundColor Gray

# Patch Package.wxs Feature block to match the locale groups we actually generated
$packageWxs = "$msiDir/Package.wxs"
$pkgContent = Get-Content $packageWxs -Raw
$localeRefs = ($localeGroupIds | ForEach-Object { "      <ComponentGroupRef Id=`"$_`" />" }) -join "`n"
$featureBlock = @"
    <Feature Id="MainFeature" Title="MyLocalBackup" Level="1">
      <ComponentGroupRef Id="AppFiles" />
$localeRefs
      <ComponentGroupRef Id="ApplicationShortcuts" />
    </Feature>
"@
$pkgContent = $pkgContent -replace '(?s)<Feature Id="MainFeature".*?</Feature>', $featureBlock
Set-Content $packageWxs -Value $pkgContent -Encoding UTF8
Write-Host "  Package.wxs Feature block updated with $($localeGroupIds.Count) locale refs" -ForegroundColor Gray

Push-Location $msiDir
wix build Package.wxs Files.wxs -d "Version=$Version" -ext WixToolset.UI.wixext -o MyLocalBackupSetup.msi
if ($LASTEXITCODE -ne 0) { Pop-Location; throw "MSI build failed" }
Pop-Location

# Verify MSI was created
if (-not (Test-Path "$msiDir\MyLocalBackupSetup.msi")) {
    throw "MSI build reported success but MyLocalBackupSetup.msi was not found"
}

# Clean up staging directory
if (Test-Path $stagingBase) { Remove-Item $stagingBase -Recurse -Force }

# Step 3: Build Burn bundle EXE (wraps MSI with custom app icon)
Write-Host "[3/5] Building setup EXE..." -ForegroundColor Yellow
# WixToolset.Bal.wixext ships its DLL as WixToolset.BootstrapperApplications.wixext.dll
$balExtDll = Join-Path $env:USERPROFILE ".wix\extensions\WixToolset.Bal.wixext\5.0.2\wixext5\WixToolset.BootstrapperApplications.wixext.dll"
if (-not (Test-Path $balExtDll)) {
    throw "WiX Bal extension not found. Install it with: wix extension add -g WixToolset.Bal.wixext/5.0.2"
}
Push-Location $msiDir
wix build Bundle.wxs -d "Version=$Version" -ext $balExtDll -o MyLocalBackupSetup.exe
if ($LASTEXITCODE -ne 0) { Pop-Location; throw "Bundle EXE build failed" }
Pop-Location

if (-not (Test-Path "$msiDir\MyLocalBackupSetup.exe")) {
    throw "Bundle build reported success but MyLocalBackupSetup.exe was not found"
}

# Step 4: Compute EXE hash
Write-Host "[4/5] Computing EXE hash..." -ForegroundColor Yellow
$exeHash = (Get-FileHash "$msiDir\MyLocalBackupSetup.exe" -Algorithm SHA256).Hash.ToLower()

# Step 5: Copy to Desktop
Write-Host "[5/5] Copying EXE to Desktop..." -ForegroundColor Yellow
Copy-Item "$msiDir\MyLocalBackupSetup.exe" "$env:USERPROFILE\Desktop\MyLocalBackupSetup_v$Version.exe" -Force

Write-Host "`n=== Build Complete ===" -ForegroundColor Green
Write-Host "EXE: $env:USERPROFILE\Desktop\MyLocalBackupSetup_v$Version.exe"
Write-Host "EXE SHA256: $exeHash"
Write-Host "`nInclude this in your GitHub release notes:"
Write-Host "SHA256: $exeHash" -ForegroundColor Cyan
