<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <ApplicationIcon>Assets\app.ico</ApplicationIcon>
    <Version>0.9.11</Version>
    <SignAssembly Condition="Exists('..\MyLocalBackup.snk')">true</SignAssembly>
    <AssemblyOriginatorKeyFile Condition="Exists('..\MyLocalBackup.snk')">..\MyLocalBackup.snk</AssemblyOriginatorKeyFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="H.NotifyIcon.Wpf" Version="2.2.0" />
    <ProjectReference Include=".\..\MyLocalBackup.Core\MyLocalBackup.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\app.ico" />
    <Resource Include="Assets\logo.png" />
  </ItemGroup>

</Project>
